### ISSUE TITLE
gradlew build throws up : NoClassDefFoundError: org/slf4j/impl/StaticLoggerBinder

### ISSUE THREAD

**Issue by prat0318** [openzipkin/zipkin-dependencies-spark#8]
When i try `.gradlew run` as per README:
i am hitting:
```
Starting a new Gradle Daemon for this build (subsequent builds will be faster).
[buildinfo] Not using buildInfo properties file for this build.
:cassandra:compileJava UP-TO-DATE
:cassandra:compileScala UP-TO-DATE
:cassandra:processResources UP-TO-DATE
:cassandra:classes UP-TO-DATE
:cassandra:run
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/impl/StaticLoggerBinder
	at org.apache.spark.Logging$class.initializeLogging(Logging.scala:116)
	at org.apache.spark.Logging$class.initializeIfNecessary(Logging.scala:107)
	at org.apache.spark.Logging$class.log(Logging.scala:51)
	at org.apache.spark.SparkContext.log(SparkContext.scala:79)
	at org.apache.spark.Logging$class.logInfo(Logging.scala:59)
	at org.apache.spark.SparkContext.logInfo(SparkContext.scala:79)
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:205)
	at org.openzipkin.dependencies.spark.cassandra.ZipkinDependenciesJob$.run(ZipkinDependenciesJob.scala:84)
	at org.openzipkin.dependencies.spark.cassandra.ZipkinDependenciesJob$.main(ZipkinDependenciesJob.scala:71)
	at org.openzipkin.dependencies.spark.cassandra.ZipkinDependenciesJob.main(ZipkinDependenciesJob.scala)
Caused by: java.lang.ClassNotFoundException: org.slf4j.impl.StaticLoggerBinder
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	... 10 more
:cassandra:run FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':cassandra:run'.
> Process 'command '/usr/lib/jvm/java-7-oracle-1.7.0.45/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 15.727 secs
```

**Comment by prat0318** [comment]
The issue went away with this patch:
```diff
diff --git a/gradle/dependencies.gradle b/gradle/dependencies.gradle
index 09a7aa4..1f78ec6 100644
--- a/gradle/dependencies.gradle
+++ b/gradle/dependencies.gradle
@@ -37,6 +37,6 @@ subprojects { subproject ->
         // Log4j is bound by Spark
         exclude group: "ch.qos.logback"
         // don't loop slf4j-log4j-slf4j
-        exclude module: "slf4j-log4j12"
+        //exclude module: "slf4j-log4j12"
      }
 }
```

I am novice in java world. But if it sounds ok, i can create a PR removing this line.

**Comment by adriancole** [comment]
Hi, Prateek. Thanks for reporting. If we need a change, likely we just need
to bind slf4j slightly differently, as we don't want to reintroduce a loop.

There might be a whack-a-mole between `./gradlew clean check` `./gradlew
cleanIdea idea` and `./gradlew clean run`. Before we change this (again
;P), can you try each? Also note that you need JRE 1.8, not 1.7

**Comment by adriancole** [comment]
org/slf4j/impl/StaticLoggerBinder is actually in the slf4j-api
dependency, which is in the classpath.

**Comment by adriancole** [comment]
There are other classpath problems. For example shadowJar doesn't
quite work yet:

$ ./gradlew shadowJar
$ java -jar ./cassandra/build/libs/cassandra-1.21.1-SNAPSHOT-all.jar
--snip--
Caused by: java.lang.ClassNotFoundException: org.apache.spark.SparkContext

Needs a little more work I think.

**Comment by adriancole** [comment]
Hint to whoever can pick this up as I have to run.

We need to make sure that `/gradlew check` and `./gradlew run` work
simultaneously. This is hard since this project has so such a vast
array of sometimes magical dependencies (due to scala, spark and
zipkin)

https://github.com/apache/spark/blob/master/core/src/main/scala/org/apache/spark/Logging.scala
